name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run build

    -   name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
            message: "Updated documentation."
            add: "docs"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
